site_name: superbox | KEBA KeEnergy API
site_url: https://api.superbox.one
site_author: Michael Hacker
site_description: A Python wrapper for the KEBA KeEnergy API used by the Web HMI.
repo_url: https://github.com/superbox-dev/keba_keenergy_api
repo_name: GitHub
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Documentation:
      - keba-keenergy/api.md
      - Endpoints:
          - keba-keenergy/api/endpoints/system.md
          - keba-keenergy/api/endpoints/buffer-tank.md
          - keba-keenergy/api/endpoints/hot-water-tank.md
          - keba-keenergy/api/endpoints/heat-pump.md
          - keba-keenergy/api/endpoints/heat-circuit.md
          - keba-keenergy/api/endpoints/solar-circuit.md
          - keba-keenergy/api/endpoints/external-heat-source.md
          - keba-keenergy/api/endpoints/switch-valve.md
          - keba-keenergy/api/endpoints/photovoltaic.md
  - Changelog: keba-keenergy/api/changelog.md
  - Contributing: keba-keenergy/api/contributing.md
  - Issues: https://github.com/superbox-dev/keba_keenergy_api/issues
  - Donation: donation.md
  - Home Assistant: https://superbox.one
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      locale: en
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            docstring_options:
              ignore_init_summary: True
            merge_init_into_class: True
            members_order: source
            show_source: False
            show_bases: False
            filters:
              - '!system'
              - '!buffer_tank'
              - '!hot_water_tank'
              - '!heat_pump'
              - '!heat_circuit'
              - '!solar_circuit'
              - '!external_heat_source'
              - '!switch_valve'
              - '!photovoltaics'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mh-superbox
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/superbox_dev
    - icon: fontawesome/brands/python
      link: https://pypi.org/user/superbox-dev/
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
